library(remotes)

install_version("ggplot2", "3.1.0")
install_version("dplyr", "0.8.0")
install_version("tidyr", "0.8.3")
install_version("broom.mixed", "0.2.4")
install_version("forcats", "0.4.0")
install_version("dagitty", "0.2-2")
install_version("MuMIn", "1.42.1")
install_version("carpenter", "0.2.1")
install_version("lme4", "1.1-21")
install_version("glue", "1.3.1")
install_version("knitr", "1.22")
install_version("purrr", "0.3.2")
install_version("stringr", "1.4.0")
